import { PageHero } from "../components/site/PageHero";
import { PageMeta } from "../lib/PageMeta";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-display text-2xl font-semibold text-foreground">{title}</h2>
      <div className="mt-3 text-muted-foreground leading-relaxed space-y-3">{children}</div>
    </section>
  );
}

export default function PrivacyPolicy() {
  return (
    <>
      <PageMeta
        title="Privacy Policy | SmartSense Technologies"
        description="How SmartSense Technologies collects, uses and protects information submitted through our website."
        ogTitle="Privacy Policy | SmartSense Technologies"
        ogDescription="Privacy practices for the SmartSense Technologies website."
      />
      <PageHero eyebrow="Privacy" title="Privacy Policy" subtitle="This policy describes how SmartSense Technologies handles information submitted through our website and business enquiry forms." />
      <article className="mx-auto max-w-3xl container-px mt-16 space-y-10 pb-16">
        <p className="text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}</p>

        <Section title="1. Information we collect">
          <p>When you complete a business enquiry form on this website, we collect the information you voluntarily provide, such as your name, organization, role, email address, phone number, sector, and the details of your enquiry or message.</p>
        </Section>

        <Section title="2. How we use information">
          <p>We use the information you provide to respond to your enquiry, schedule meetings or demonstrations, manage related business communications, and improve our solutions and services. We do not sell personal information.</p>
        </Section>

        <Section title="3. Email marketing & CRM processing">
          <p>SmartSense may use an email marketing and CRM platform (such as Brevo, placeholder) to manage business communications, track engagement and organize relationships with prospects, partners and clients. Your information may be processed by such platforms strictly to support these business communications.</p>
        </Section>

        <Section title="4. Anti-spam protection">
          <p>We use Cloudflare Turnstile (placeholder) to help protect our forms from automated abuse. Cloudflare may process limited technical information from your browser to verify that submissions are not generated by bots.</p>
        </Section>

        <Section title="5. Website analytics">
          <p>We may use privacy-aware website analytics (placeholder) to understand aggregate traffic patterns and improve site performance. Analytics data is used in aggregate and does not aim to personally identify visitors.</p>
        </Section>

        <Section title="6. Data retention">
          <p>We retain enquiry information only for as long as necessary to respond to your request and maintain a reasonable record of business communications, in line with applicable laws.</p>
        </Section>

        <Section title="7. Your rights">
          <p>You may request access, correction or deletion of personal information we hold about you, subject to applicable law. To make such a request, contact us using the details below.</p>
        </Section>

        <Section title="8. Important notice">
          <p>Please do <span className="font-semibold text-foreground">not</span> submit sensitive health, financial, personal identity or confidential government information through public website forms. For sensitive matters, contact us to arrange a secure channel.</p>
        </Section>

        <Section title="9. Contact">
          <p>For privacy enquiries, contact us via the <a className="text-secondary underline underline-offset-4" href="/contact">Contact page</a> or at privacy@smartsense.africa (placeholder).</p>
        </Section>
      </article>
    </>
  );
}