/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as InnovationPortfolioRouteImport } from './routes/innovation-portfolio'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsMixedRealityRouteImport } from './routes/solutions.mixed-reality'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationPortfolioRoute = InnovationPortfolioRouteImport.update({
  id: '/innovation-portfolio',
  path: '/innovation-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsMixedRealityRoute = SolutionsMixedRealityRouteImport.update({
  id: '/solutions/mixed-reality',
  path: '/solutions/mixed-reality',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/government': typeof GovernmentRoute
  '/industries': typeof IndustriesRoute
  '/innovation-portfolio': typeof InnovationPortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/thank-you': typeof ThankYouRoute
  '/solutions/mixed-reality': typeof SolutionsMixedRealityRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/government': typeof GovernmentRoute
  '/industries': typeof IndustriesRoute
  '/innovation-portfolio': typeof InnovationPortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/thank-you': typeof ThankYouRoute
  '/solutions/mixed-reality': typeof SolutionsMixedRealityRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/government': typeof GovernmentRoute
  '/industries': typeof IndustriesRoute
  '/innovation-portfolio': typeof InnovationPortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/thank-you': typeof ThankYouRoute
  '/solutions/mixed-reality': typeof SolutionsMixedRealityRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/government'
    | '/industries'
    | '/innovation-portfolio'
    | '/privacy-policy'
    | '/thank-you'
    | '/solutions/mixed-reality'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/government'
    | '/industries'
    | '/innovation-portfolio'
    | '/privacy-policy'
    | '/thank-you'
    | '/solutions/mixed-reality'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/government'
    | '/industries'
    | '/innovation-portfolio'
    | '/privacy-policy'
    | '/thank-you'
    | '/solutions/mixed-reality'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GovernmentRoute: typeof GovernmentRoute
  IndustriesRoute: typeof IndustriesRoute
  InnovationPortfolioRoute: typeof InnovationPortfolioRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ThankYouRoute: typeof ThankYouRoute
  SolutionsMixedRealityRoute: typeof SolutionsMixedRealityRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation-portfolio': {
      id: '/innovation-portfolio'
      path: '/innovation-portfolio'
      fullPath: '/innovation-portfolio'
      preLoaderRoute: typeof InnovationPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/mixed-reality': {
      id: '/solutions/mixed-reality'
      path: '/solutions/mixed-reality'
      fullPath: '/solutions/mixed-reality'
      preLoaderRoute: typeof SolutionsMixedRealityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GovernmentRoute: GovernmentRoute,
  IndustriesRoute: IndustriesRoute,
  InnovationPortfolioRoute: InnovationPortfolioRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ThankYouRoute: ThankYouRoute,
  SolutionsMixedRealityRoute: SolutionsMixedRealityRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
